update readme
aws/aws-iot-fleetwise-edge pull request #24
Opened 2022-11-07 15:46 UTC by manohartc2020

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-07 15:52 UTC, hefroy requested changes

2022-11-07 15:52 UTC, hefroy commented on README.md
> +AAWS IoT FleetWise is a service that makes it easy for Automotive OEMs, Fleet operators, Independent Software vendors (ISVs)  to collect, store, organize, and monitor data from vehicles at scale. Edg
Typo: AWS

2022-11-07 15:52 UTC, hefroy commented on README.md
> +>   ℹ️  To quickly get started, jump to the [Developer Guide](./docs/dev-guide/edge-agent-dev-guide.md)
Recommend to stay with `:information_source:` rather than utf-8 emoji

2022-11-07 23:45 UTC, csxwin requested changes

2022-11-07 23:45 UTC, csxwin commented on README.md
> +AWS IoT FleetWise is a service that makes it easy for Automotive OEMs, Fleet operators, Independent Software vendors (ISVs)  to collect, store, organize, and monitor data from vehicles at scale. Edge
please remove `pre-configured analytic capabilities`.

2022-11-09 18:10 UTC, csxwin approved these changes

2022-11-09 18:41 UTC, merged